name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Package with Maven
        run: mvn --file code/pom.xml --batch-mode --update-snapshots package
      - name: Add API docs
        run: mv ./code/annotations/target/apidocs ./code/annotations/target/site/
      - name: Add the base index
        run: cp ./docs/* ./code/annotations/target/site
      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: github.ref == 'refs/heads/dev11'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        if: github.ref == 'refs/heads/dev11'
        with:
          path: './code/annotations/target/site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/dev11'



# CI docs:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# https://github.com/actions/cache/blob/master/examples.md#java---maven
# https://github.com/marketplace/actions/github-pages-action
# https://github.com/actions/setup-java/blob/main/README.md
