name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17', '20' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.Java }}'
          distribution: 'temurin'
      - name: Package with Maven
        run: mvn --file code/pom.xml --batch-mode --update-snapshots package
  # https://github.com/marketplace/actions/github-pages-action
  document:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Javadoc with Maven
        run: mvn --file code/pom.xml --batch-mode javadoc:javadoc
      - name: Add the base index
        run: cp ./docs/* ./code/target/site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./code/target/site
